name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Configure and build the project
    - name: Build
      run: |
        mkdir build
        mkdir build/Parser
        mkdir build/Emulator
        make
